"""add level range to questions

Revision ID: 29b88a5502f4
Revises: 5a1c221f9903
Create Date: 2026-07-26 20:09:59.403555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b88a5502f4'
down_revision: Union[str, None] = '5a1c221f9903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('min_level', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('max_level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'max_level')
    op.drop_column('questions', 'min_level')
    # ### end Alembic commands ###
