"""add reference card skills and card rarity

Revision ID: 70d747a00bf7
Revises: 29b88a5502f4
Create Date: 2026-07-26 21:15:21.859409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d747a00bf7'
down_revision: Union[str, None] = '29b88a5502f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_card_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_card_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_card_id'], ['reference_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'reference_cards',
        sa.Column('overall_rarity', sa.String(), nullable=False, server_default=''),
    )
    op.add_column(
        'reference_cards',
        sa.Column('role', sa.String(), nullable=False, server_default=''),
    )
    op.alter_column('reference_cards', 'overall_rarity', server_default=None)
    op.alter_column('reference_cards', 'role', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference_cards', 'role')
    op.drop_column('reference_cards', 'overall_rarity')
    op.drop_table('reference_card_skills')
    # ### end Alembic commands ###
